export const CHANGE_SEARCH_QUERY = 'CHANGE_SEARCH_QUERY';
export const SEND_SEARCH_REQUEST = 'SEND_SEARCH_REQUEST';
export const GET_REQUEST_SUCCESS = 'GET_REQUEST_SUCCESS';
export const GET_REQUEST_FAILURE = 'GET_REQUEST_FAILURE';